// <auto-generated />
namespace WebWIthIdentity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fieldaddedpropertylastupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fieldaddedpropertylastupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201508101709300_Field added property 'last updated'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
