// <auto-generated />
namespace HiveServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MadeDatetimeonnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MadeDatetimeonnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201511220017145_Made Datetime on-nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
